### ISSUE TITLE
ruby 2.5.1 timeout error

### ISSUE THREAD

**Issue by noraj** [rverton/DrupalScan#2]
Hi, I'm tested with ruby 2.5.1 and a timeout error seems not handled: 
 ```
$ DrupalScan -u http://xxx/
Traceback (most recent call last):
        18: from /home/noraj/.rbenv/versions/2.5.1/bin/DrupalScan:23:in `<main>'
        17: from /home/noraj/.rbenv/versions/2.5.1/bin/DrupalScan:23:in `load'
        16: from /home/noraj/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/DrupalScan-0.5.2/bin/DrupalScan:32:in `<top (required)>'                                                                              
        15: from /home/noraj/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/DrupalScan-0.5.2/lib/DrupalScan.rb:7:in `getVersion'                                                                                  
        14: from /home/noraj/.rbenv/versions/2.5.1/lib/ruby/2.5.0/open-uri.rb:35:in `open'
        13: from /home/noraj/.rbenv/versions/2.5.1/lib/ruby/2.5.0/open-uri.rb:735:in `open'
        12: from /home/noraj/.rbenv/versions/2.5.1/lib/ruby/2.5.0/open-uri.rb:165:in `open_uri'
        11: from /home/noraj/.rbenv/versions/2.5.1/lib/ruby/2.5.0/open-uri.rb:224:in `open_loop'
        10: from /home/noraj/.rbenv/versions/2.5.1/lib/ruby/2.5.0/open-uri.rb:224:in `catch'
         9: from /home/noraj/.rbenv/versions/2.5.1/lib/ruby/2.5.0/open-uri.rb:226:in `block in open_loop'                                                                                                         
         8: from /home/noraj/.rbenv/versions/2.5.1/lib/ruby/2.5.0/open-uri.rb:755:in `buffer_open'
         7: from /home/noraj/.rbenv/versions/2.5.1/lib/ruby/2.5.0/open-uri.rb:337:in `open_http'
         6: from /home/noraj/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:909:in `start'
         5: from /home/noraj/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
         4: from /home/noraj/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:935:in `connect'
         3: from /home/noraj/.rbenv/versions/2.5.1/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
         2: from /home/noraj/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:937:in `block in connect'
         1: from /home/noraj/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:937:in `open'
/home/noraj/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:937:in `initialize': execution expired (Net::OpenTimeout)
```

**Comment by rverton** [comment]
Hi @noraj,
sorry this project is not maintained anymore. Feel free to fix this for yourself. Also it looks like the host you are trying to contact is timing out.

Greetings

**Comment by noraj** [comment]
Yes the host was timing out, but a tool should close nicely and display and error rather than raise an uncaught error. But is the project is not maintain can you (even if it seems obvious I agree) can you archive the repo ? https://help.github.com/articles/archiving-repositories/
So the warning archive banner will be obvious for anyone.
